title: The Shining Stash
author:
  name: shinyfinder
description: >- # this means to ignore newlines until "baseurl:"
  A collection of open source tools and resources for the Pokemon community.
baseurl: "" # the subpath of your site, e.g. /blog
domain: shinyfinder.gihub.io
url: "https://shinyfinder.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: G-BPGB43X3QR

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { icon: "github", title: "GitHub", url: "https://github.com/shinyfinder" }
    - { icon: "user", title: "Smogon", url: "https://www.smogon.com/forums/members/shiny-finder.206479/" }
    - { icon: "reddit-alien", title: "Reddit", url: "https://www.reddit.com/user/shi_fi/" }


header_pages:
  - about.md
  - tools/tools.md
  - tools/swiss/index.html
  - encounter-slots/slots.md

show_excerpts: false # set to true to show excerpts on the homepage

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
