title: The Shining Stash
author:
  name: shinyfinder
description: >- # this means to ignore newlines until "baseurl:"
  A collection of open source tools and resources for the Pokemon community.
baseurl: "" # the subpath of your site, e.g. /blog
domain: shinyfinder.gihub.io
url: "https://shinyfinder.github.io" # the base hostname & protocol for your site, e.g. http://example.com


minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github, user_url: "https://github.com/shinyfinder" }

header_pages:
  - about.md
  - tools/tools.md
  - projects/projects.md
  - go-weather/index.html

show_excerpts: false # set to true to show excerpts on the homepage

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
